version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4  # Updated to match your client version
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Limit memory usage
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy